<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <style>
        body {
            font-family: 'Arial', sans-serif;
        }

        .sidebar {
            background-color: #2c3e50;
            color: white;
            height: 100vh;
            padding-top: 50px;
        }

        .sidebar a {
            color: white;
            text-decoration: none;
            padding: 10px;
            display: block;
            margin: 10px 0;
        }

        .sidebar a:hover {
            background-color: #34495e;
        }

        .main-content {
            margin-left: 250px;
            padding: 20px;
        }

        .card {
            margin: 10px 0;
        }

        .card-header {
            background-color: #3498db;
            color: white;
        }

        .card-body {
            background-color: #f7f7f7;
        }
    </style>
</head>

<body>

    <div class="d-flex">
        <!-- Sidebar -->
        <div class="sidebar p-3">
            <h3>User Dashboard</h3>
            <a href="/admin-dashboard">Dashboard</a>
            <a href="/admin-dashboard/users">Users</a>
            <a href="/admin-dashboard/settings">Settings</a>
            <a href="/admin-dashboard/reports">Reports</a>
            <a href="/logout"
                onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>

        </div>

        <!-- Main Content -->
        <div class="main-content">
            <div class="container">
                <h1 class="my-4">Welcome to the Admin Dashboard</h1>

                <div class="row">
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-header">Total Users</div>
                            <div class="card-body">
                                <h4>100</h4>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-header">Active Sessions</div>
                            <div class="card-body">
                                <h4>50</h4>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-header">New Reports</div>
                            <div class="card-body">
                                <h4>20</h4>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row mt-5">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">Recent Activities</div>
                            <div class="card-body">
                                <ul>
                                    <li>User John Doe created a new post.</li>
                                    <li>User Jane Smith updated profile details.</li>
                                    <li>Report generated by Admin.</li>
                                    <li>System maintenance scheduled for tomorrow.</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>
